# Site settings
title: Welcome to Project Daisec!

INTRODUCTION
Our project DAISEC (Data Analytics In cyberSECurity) aims to incorporate hands-on teaching of data analytics in cybersecurity. To that end, we create three hands-on teaching modules that incorporates authentic analytics based solutions for cybersecurity related problems.

We hope to these hands-on materials: 
•	Help the cybersecurity community to train a new generation of cyber security professionals who would understand and be able to implement data analytics in cybersecurity problems;  

•	Enrich the current cybersecurity curriculum to attract students studying in computing, 

•	Introduce cybersecurity as a new knowledge area for Information Systems students for future career choices, and 

•	Bridge the gap between the current curriculum and industry expectations by introducing an emerging knowledge area. 

Please go to [modules](https://daisecpace.github.io/modules/) section to access materials for each module.    
Acknowledgment

The author(s) would like to acknowledge the support from the Department of Defense under CNAP Grant No. H98230-17-1-0335. 
Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Department of Defense or the U.S. government.


email: 
description: > # this means to ignore newlines until "baseurl:"
  Project Daisec
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diezcami.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
